import { parseCSV, normalizeRows } from './core/ingestion/csv.js';
import { inferSchema, profileDataset, qualityReport } from './core/profiling/profile.js';
import { aggregate, groupBy, compare } from './core/analytics/engine.js';
import { createEvidence } from './core/evidence/model.js';
import { put, all } from './core/storage/indexeddb.js';
import { AIProviderRegistry, createAIRequest } from './core/ai/provider.js';
import { OpenAICompatibleProvider } from './providers/openai-compatible.js';

const APP_KEY='ai-analytics-builder-v1';
const DEFAULT={project:{name:'AI Analytics Tool',goal:'Build a production-oriented personal AI analytics tool that turns datasets into evidence-backed investigations and insights.',status:'Architecture / MVP definition',version:'0.1'},decisions:[{id:'d1',title:'Deterministic analytics first',text:'Numerical truth comes from the analytical engine; the LLM interprets verified results.',status:'accepted'},{id:'d2',title:'Investigation Engine is the core differentiator',text:'Natural-language questions become structured investigations with evidence.',status:'accepted'},{id:'d3',title:'Local-first PWA',text:'Project state, notes, tasks and specifications remain in browser storage.',status:'accepted'}],tasks:[{id:'t1',title:'Define domain model',phase:'Architecture',status:'done'},{id:'t2',title:'Define analysis DSL',phase:'Architecture',status:'done'},{id:'t3',title:'Build deterministic analytics engine',phase:'MVP',status:'todo'},{id:'t4',title:'Build investigation engine',phase:'MVP',status:'todo'},{id:'t5',title:'Add evidence-backed AI synthesis',phase:'MVP',status:'todo'},{id:'t6',title:'Create synthetic evaluation dataset',phase:'Validation',status:'todo'}],notes:'Keep the core domain-agnostic. Web3 can be added later as a connector. Avoid premature microservices.',files:[],messages:[],spec:{vision:'A structured analytical workspace combining deterministic analytics with AI-assisted investigation, explanation, visualization, anomaly detection and evidence-backed insights.',principles:['Deterministic first','Evidence-backed AI','Human remains in control','Domain-agnostic core','Reproducible analysis'],mvp:['CSV upload','Schema inference','Data profiling','Data quality','Interactive exploration','Natural-language question','Analysis DSL','Investigation Engine','Evidence-backed AI synthesis','Insight cards','Analysis history']}};
function load(){try{return JSON.parse(localStorage.getItem(APP_KEY))||structuredClone(DEFAULT)}catch{return structuredClone(DEFAULT)}}
function save(s){localStorage.setItem(APP_KEY,JSON.stringify(s))}
function esc(s){return String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function el(tag,attrs={},children=[]){const e=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==='class')e.className=v;else if(k==='onclick')e.onclick=v;else e.setAttribute(k,v)}for(const c of children)e.append(typeof c==='string'?document.createTextNode(c):c);return e}
let state=load(); let active='overview';
const aiRegistry=new AIProviderRegistry();
let currentDataset=null;
const root=document.getElementById('root');
function render(){root.innerHTML='';root.append(app());}
function app(){const wrap=el('div',{class:'app'});wrap.append(sidebar());const main=el('main',{class:'main'});main.append(topbar());const content=el('div',{class:'content'});content.append(active==='overview'?overview():active==='architecture'?architecture():active==='tasks'?tasks():active==='decisions'?decisions():active==='spec'?spec():active==='files'?files():active==='data'?data():active==='chat'?chat():overview());main.append(content);wrap.append(main);return wrap}
function sidebar(){const s=el('aside',{class:'sidebar'});s.innerHTML=`<div class="brand"><div class="brand-row"><div class="logo">AI</div><div><b>Analytics Builder</b><small>local-first workspace</small></div></div></div><nav class="nav"></nav><div class="side-bottom">State: local<br>Project data stays in this browser unless AI chat is explicitly used.</div>`;const nav=[['overview','⌂','Overview'],['architecture','◈','Architecture'],['tasks','✓','Build Tasks'],['decisions','◇','Decisions'],['spec','≡','Product Spec'],['files','□','Files & Context'],['data','▦','Data & Analytics'],['chat','✦','AI Architect']];const n=s.querySelector('.nav');nav.forEach(([id,icon,txt])=>{const b=el('button',{class:active===id?'active':''});b.innerHTML=`<span>${icon}</span><span class="txt">${txt}</span>`;b.onclick=()=>{active=id;render()};n.append(b)});return s}
function topbar(){const h=el('header',{class:'topbar'});h.innerHTML=`<div><div class="title">${esc(state.project.name)}</div><div class="subtitle">${esc(state.project.status)} · local PWA</div></div><div class="actions"></div>`;const a=h.querySelector('.actions');[['Export','export'],['Reset','reset']].forEach(([t,id])=>{const b=el('button',{class:'btn'});b.textContent=t;b.onclick=()=>id==='export'?exportState():resetState();a.append(b)});return h}
function overview(){const d=el('div',{class:'grid'});d.innerHTML=`<section class="card span-8"><div class="eyebrow">Project mission</div><div class="h1">Build an AI analytical workstation.</div><p class="lead">${esc(state.project.goal)}</p><div style="height:16px"></div><div class="stats"><div class="stat"><div class="n">${state.tasks.filter(x=>x.status==='done').length}/${state.tasks.length}</div><div class="l">tasks completed</div></div><div class="stat"><div class="n">${state.decisions.length}</div><div class="l">architecture decisions</div></div><div class="stat"><div class="n">${state.files.length}</div><div class="l">local context files</div></div><div class="stat"><div class="n">${state.messages.length}</div><div class="l">AI messages</div></div></div></section><section class="card span-4"><div class="eyebrow">Build progress</div><div class="section-title">MVP readiness</div><div class="progress"><i style="width:${Math.round(state.tasks.filter(x=>x.status==='done').length/state.tasks.length*100)}%"></i></div><p class="lead" style="font-size:12px">${Math.round(state.tasks.filter(x=>x.status==='done').length/state.tasks.length*100)}% of the current build checklist.</p><button class="btn primary" id="goTasks">Continue build →</button></section><section class="card span-8"><div class="eyebrow">Core pipeline</div><div class="roadmap">${['Data ingestion','Profiling & quality','Explore & detect','Investigation Engine','Evidence layer','AI synthesis','Insights & reports'].map((x,i)=>`<div class="row"><span><b>${i+1}. ${x}</b></span><span class="badge ${i<2?'b-green':i===3?'b-amber':'b-blue'}">${i<2?'foundation':i===3?'core':'planned'}</span></div>`).join('')}</div></section><section class="card span-4"><div class="eyebrow">Operating rule</div><div class="danger-note">Never let the LLM become the numerical source of truth. AI proposes and interprets; deterministic analytics verifies.</div><div style="height:10px"></div><div class="chips"><span class="chip">Local-first</span><span class="chip">Evidence</span><span class="chip">Reproducible</span><span class="chip">Domain-agnostic</span></div></section>`;d.querySelector('#goTasks').onclick=()=>{active='tasks';render()};return d}
function architecture(){const d=el('div',{class:'grid'});d.innerHTML=`<section class="card span-8"><div class="eyebrow">Architecture</div><div class="h1">Deterministic core + AI investigation layer</div><p class="lead">The architecture intentionally separates computation from interpretation.</p><div class="card" style="margin-top:14px;background:#0b1320"><pre class="code" style="white-space:pre-wrap;color:#b9d9f2;line-height:1.65">User question
    ↓
AI → structured Analysis Plan / DSL
    ↓
Validation
    ↓
Deterministic Analytics Engine
    ↓
Verified Evidence
    ↓
AI → explanation / hypothesis / insight
    ↓
Report</pre></div></section><section class="card span-4"><div class="eyebrow">Modules</div><div class="list">${['data-ingestion','data-profiling','data-quality','analytics-core','analysis-dsl','investigation-engine','evidence','visualization','ai-core','reports','persistence','observability'].map(x=>`<div class="row"><span class="code">${x}</span><span class="badge b-blue">module</span></div>`).join('')}</div></section><section class="card span-12"><div class="eyebrow">Recommended implementation boundary</div><div class="two"><div><b>MVP</b><p class="lead">CSV → profiling → deterministic analytics → natural-language question → investigation → evidence → AI synthesis.</p></div><div><b>Later</b><p class="lead">PostgreSQL/API connectors, scheduled analysis, Web3 connectors, advanced statistics and optional code sandbox.</p></div></div></section>`;return d}
function tasks(){const d=el('div',{class:'grid'});d.innerHTML=`<section class="card span-8"><div class="eyebrow">Build queue</div><div class="section-title">Implementation tasks</div><div class="list task-list"></div><div style="display:flex;gap:8px;margin-top:12px"><input class="input" id="newTask" placeholder="Add implementation task…"><button class="btn primary" id="addTask">Add</button></div></section><section class="card span-4"><div class="eyebrow">Execution rule</div><p class="lead">Complete architecture contracts before large UI work. Every phase must have tests and a verifiable acceptance condition.</p></section>`;const list=d.querySelector('.task-list');state.tasks.forEach(t=>{const r=el('div',{class:'row'});r.innerHTML=`<div><b>${esc(t.title)}</b><div class="meta">${esc(t.phase)}</div></div><div><span class="badge ${t.status==='done'?'b-green':'b-amber'}">${t.status}</span> <button class="btn" style="padding:4px 7px">${t.status==='done'?'↩':'✓'}</button></div>`;r.querySelector('button').onclick=()=>{t.status=t.status==='done'?'todo':'done';save(state);render()};list.append(r)});d.querySelector('#addTask').onclick=()=>{const x=d.querySelector('#newTask');if(x.value.trim()){state.tasks.push({id:uid(),title:x.value.trim(),phase:'MVP',status:'todo'});save(state);render()}};return d}
function decisions(){const d=el('div',{class:'grid'});d.innerHTML=`<section class="card span-8"><div class="eyebrow">Architecture decisions</div><div class="list decisions"></div></section><section class="card span-4"><div class="eyebrow">New decision</div><div class="form"><input class="input" id="dt" placeholder="Decision title"><textarea class="textarea" id="dx" placeholder="Decision, rationale and consequences"></textarea><button class="btn primary" id="addD">Save decision</button></div></section>`;const l=d.querySelector('.decisions');state.decisions.forEach(x=>{const r=el('div',{class:'row'});r.innerHTML=`<div><b>${esc(x.title)}</b><div class="meta">${esc(x.text)}</div></div><span class="badge b-green">${x.status}</span>`;l.append(r)});d.querySelector('#addD').onclick=()=>{const t=d.querySelector('#dt'),x=d.querySelector('#dx');if(t.value.trim()&&x.value.trim()){state.decisions.push({id:uid(),title:t.value.trim(),text:x.value.trim(),status:'accepted'});save(state);render()}};return d}
function spec(){const d=el('div',{class:'grid'});d.innerHTML=`<section class="card span-8"><div class="eyebrow">Product specification</div><div class="section-title">Vision</div><textarea class="textarea" id="vision">${esc(state.spec.vision)}</textarea><div style="height:12px"></div><div class="section-title">MVP scope</div><div class="list">${state.spec.mvp.map(x=>`<div class="row"><span>${esc(x)}</span><span class="check">✓</span></div>`).join('')}</div><button class="btn primary" id="saveSpec" style="margin-top:12px">Save changes</button></section><section class="card span-4"><div class="eyebrow">Principles</div><div class="list">${state.spec.principles.map((x,i)=>`<div class="row"><span>${i+1}. ${esc(x)}</span></div>`).join('')}</div></section>`;d.querySelector('#saveSpec').onclick=()=>{state.spec.vision=d.querySelector('#vision').value;save(state);toast('Specification saved');};return d}
function files(){const d=el('div',{class:'grid'});d.innerHTML=`<section class="card span-8"><div class="eyebrow">Context library</div><div class="drop" id="drop">Drop project files here or <label style="color:var(--cyan);cursor:pointer">browse<input id="fileInput" type="file" multiple hidden></label><div style="font-size:10px;margin-top:6px">MD · TXT · JSON · CSV · SQL · TS · JS · YAML · PDF (metadata only in local builder)</div></div><div class="list" id="fl" style="margin-top:12px"></div></section><section class="card span-4"><div class="eyebrow">Operator notes</div><textarea class="textarea" id="notes">${esc(state.notes)}</textarea><button class="btn primary" id="saveNotes" style="margin-top:8px">Save notes</button></section>`;const input=d.querySelector('#fileInput');input.onchange=()=>addFiles(input.files);d.querySelector('#drop').ondragover=e=>{e.preventDefault();};d.querySelector('#drop').ondrop=e=>{e.preventDefault();addFiles(e.dataTransfer.files)};function list(){const l=d.querySelector('#fl');l.innerHTML=state.files.length?state.files.map(f=>`<div class="row file"><div><b>${esc(f.name)}</b><div class="meta">${esc(f.type||'text')} · ${f.size} bytes</div></div><button class="btn danger">Remove</button></div>`).join(''):'<div class="empty" style="min-height:160px">No context files yet.</div>';[...l.querySelectorAll('button')].forEach((b,i)=>b.onclick=()=>{state.files.splice(i,1);save(state);list()})}async function addFiles(fs){for(const f of fs){if(f.size>2*1024*1024){toast('File too large: '+f.name);continue}let text='';if(/^(text|application\/json)/.test(f.type)||/\.(md|txt|json|csv|sql|ts|tsx|js|jsx|yaml|yml)$/i.test(f.name))text=await f.text();state.files.push({id:uid(),name:f.name,type:f.type,size:f.size,content:text.slice(0,300000)});}save(state);list()}list();d.querySelector('#saveNotes').onclick=()=>{state.notes=d.querySelector('#notes').value;save(state);toast('Notes saved')};return d}
function chat(){const d=el('div',{class:'chat'});d.innerHTML=`<div class="messages" id="msgs"></div><div class="card" style="border-radius:0;border-left:0;border-right:0"><div class="eyebrow">Optional AI provider</div><div class="two"><input class="input" id="aiEndpoint" placeholder="Endpoint (e.g. http://localhost:11434/v1/chat/completions)"><input class="input" id="aiModel" placeholder="Model (e.g. llama3.2)"></div><div style="height:8px"></div><div style="display:flex;gap:8px"><input class="input" id="aiKey" type="password" placeholder="API key — optional for local providers"><button class="btn" id="saveAI">Save provider</button></div><div class="meta" style="margin-top:7px">No provider is required. The analytics engine remains fully local. Browser-side API keys are stored locally and should only be used on a trusted machine.</div></div><div class="composer"><textarea class="textarea" id="prompt" placeholder="Ask for an analysis plan, architecture review, or evidence interpretation…"></textarea><button class="btn primary" id="send">Send</button></div>`;const m=d.querySelector('#msgs');if(!state.messages.length){m.innerHTML='<div class="empty"><div><strong>AI Architect</strong>Optional AI layer. Configure any OpenAI-compatible endpoint, or leave it disabled and keep working locally.<div style="margin-top:10px" class="chips"><span class="chip">Analysis DSL</span><span class="chip">Architecture review</span><span class="chip">Evidence interpretation</span></div></div></div>'}else state.messages.forEach(x=>{const e=el('div',{class:'msg '+x.role});e.innerHTML=esc(x.content);m.append(e)});const cfg=state.ai||{};d.querySelector('#aiEndpoint').value=cfg.endpoint||'';d.querySelector('#aiModel').value=cfg.model||'';d.querySelector('#aiKey').value=cfg.apiKey||'';d.querySelector('#saveAI').onclick=()=>{state.ai={endpoint:d.querySelector('#aiEndpoint').value.trim(),model:d.querySelector('#aiModel').value.trim(),apiKey:d.querySelector('#aiKey').value};save(state);toast('AI provider settings saved')};d.querySelector('#send').onclick=send;d.querySelector('#prompt').onkeydown=e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();send()}};return d}

async function send(){const box=document.querySelector('#prompt'),q=box?.value.trim();if(!q)return;state.messages.push({role:'user',content:q});save(state);active='chat';render();const cfg=state.ai||{};if(!cfg.endpoint){state.messages.push({role:'assistant',content:'No AI provider is configured. This is intentional: AI is optional. Configure an OpenAI-compatible endpoint above, or continue with local deterministic analytics.'});save(state);render();return;}const provider=new OpenAICompatibleProvider({endpoint:cfg.endpoint,apiKey:cfg.apiKey,model:cfg.model||'local-model'});aiRegistry.register(provider);const context=`PROJECT: ${state.project.name}\nGOAL: ${state.project.goal}\nDECISIONS:\n${state.decisions.map(x=>'- '+x.title+': '+x.text).join('\n')}\nTASKS:\n${state.tasks.map(x=>'- ['+x.status+'] '+x.title).join('\n')}\nSPEC: ${state.spec.vision}\nANALYTICS RULE: numerical truth must come from deterministic analytics and verified evidence.`;try{const response=await provider.analyze(createAIRequest('architecture', {system:`You are the senior AI architect for a local-first AI Analytics Builder. Be concrete, critical and evidence-aware. Never invent numerical evidence.\n${context}`}, q));state.messages.push({role:'assistant',content:typeof response.content==='string'?response.content:JSON.stringify(response.content,null,2)});}catch(e){state.messages.push({role:'assistant',content:'AI provider error: '+e.message});}save(state);render()}

function data(){const d=el('div',{class:'grid'});d.innerHTML=`<section class="card span-8"><div class="eyebrow">Local data runtime</div><div class="h1">CSV → Schema → Profile → Evidence</div><p class="lead">This pipeline runs in the browser. No backend and no AI provider are required.</p><div class="drop" id="dataDrop">Choose a CSV file <label style="color:var(--cyan);cursor:pointer">browse<input id="csvInput" type="file" accept=".csv,text/csv" hidden></label><div style="font-size:10px;margin-top:6px">The raw dataset is kept in IndexedDB.</div></div><div id="datasetView" style="margin-top:12px"></div></section><section class="card span-4"><div class="eyebrow">Deterministic operations</div><div class="list"><div class="row"><span>schema inference</span><span class="badge b-green">local</span></div><div class="row"><span>data profile</span><span class="badge b-green">local</span></div><div class="row"><span>quality checks</span><span class="badge b-green">local</span></div><div class="row"><span>aggregation</span><span class="badge b-green">local</span></div><div class="row"><span>evidence</span><span class="badge b-green">verified</span></div></div></section><section class="card span-12" id="analysisPanel" style="display:none"></section>`;
const input=d.querySelector('#csvInput');input.onchange=()=>input.files[0]&&loadDataset(input.files[0]);
async function loadDataset(file){const text=await file.text();const parsed=parseCSV(text);const rows=normalizeRows(parsed.rows);const schema=inferSchema(rows,parsed.columns);const dataset={id:crypto.randomUUID(),name:file.name,createdAt:new Date().toISOString(),columns:parsed.columns,rows,schema,profile:profileDataset(rows,schema),quality:qualityReport(rows,schema)};await put('datasets',dataset);currentDataset=dataset;renderDataset();}
function renderDataset(){const v=d.querySelector('#datasetView');if(!currentDataset){v.innerHTML='<div class="empty" style="min-height:180px">No dataset loaded yet.</div>';return;}const p=currentDataset.profile;v.innerHTML=`<div class="stats"><div class="stat"><div class="n">${p.rowCount}</div><div class="l">rows</div></div><div class="stat"><div class="n">${p.columns}</div><div class="l">columns</div></div><div class="stat"><div class="n">${p.nullCells}</div><div class="l">null cells</div></div><div class="stat"><div class="n">${p.duplicateRows}</div><div class="l">duplicate rows</div></div></div><div style="height:12px"></div><div class="section-title">${esc(currentDataset.name)}</div><div class="list">${currentDataset.schema.map(c=>`<div class="row"><span><b>${esc(c.name)}</b><div class="meta">${c.type} · ${c.uniqueCount} unique${c.nullCount?' · '+c.nullCount+' null':''}</div></span><span class="badge ${c.type==='number'?'b-blue':'b-purple'}">${c.type}</span></div>`).join('')}</div><div style="height:12px"></div><div class="danger-note">${currentDataset.quality.length?currentDataset.quality.map(q=>`${esc(q.severity)}: ${esc(q.code)}${q.column?' — '+esc(q.column):''}${q.count?' ('+q.count+')':''}`).join('<br>'):'No basic quality issues detected.'}</div><button class="btn primary" id="explore">Run deterministic analysis</button>`;d.querySelector('#explore').onclick=()=>analysis(currentDataset);}
async function analysis(ds){const numeric=ds.schema.filter(c=>c.type==='number');const panel=d.querySelector('#analysisPanel');panel.style.display='block';if(!numeric.length){panel.innerHTML='<div class="eyebrow">Analysis</div><p class="lead">No numeric columns were detected. The dataset is profiled but there is no metric to aggregate yet.</p>';return;}const metric=numeric[0].name;const result={metric,operation:'sum',value:aggregate(ds.rows,metric,'sum'),average:aggregate(ds.rows,metric,'avg'),min:aggregate(ds.rows,metric,'min'),max:aggregate(ds.rows,metric,'max')};const evidence=createEvidence({type:'metric',datasetId:ds.id,operation:'aggregate',input:{field:metric},result});await put('evidence',evidence);panel.innerHTML=`<div class="eyebrow">Verified evidence</div><div class="section-title">${esc(metric)}</div><div class="stats"><div class="stat"><div class="n">${result.value}</div><div class="l">SUM</div></div><div class="stat"><div class="n">${Number(result.average).toFixed(2)}</div><div class="l">AVG</div></div><div class="stat"><div class="n">${result.min}</div><div class="l">MIN</div></div><div class="stat"><div class="n">${result.max}</div><div class="l">MAX</div></div></div><p class="lead" style="margin-top:10px">Evidence ID: <span class="code">${evidence.id}</span> · deterministic: true</p>`;}
renderDataset();return d}

function toast(t){const x=el('div',{class:'toast'});x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),1800)}
function exportState(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ai-analytics-builder-state.json';a.click();URL.revokeObjectURL(a.href)}
function resetState(){if(confirm('Reset the local project state?')){state=structuredClone(DEFAULT);save(state);render()}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
